import { light } from '@sumup-oss/design-tokens';

/**
 * Design Tokens
 * 
 * Centralized tokens that map Circuit UI design system values to the application's needs.
 * This replaces the MUI theme system for most parts of the app.
 */
export const tokens = {
    direction: 'ltr' as 'ltr' | 'rtl',
    spacing: (...args: number[]) => args.map((value) => `${value * 8}px`).join(' '),
    colors: {
        primary: {
            lighter: 'var(--cui-bg-accent-hovered)',
            light: 'var(--cui-bg-accent-hovered)',
            main: 'var(--cui-bg-accent)',
            dark: 'var(--cui-bg-accent-pressed)',
            darker: 'var(--cui-fg-accent)',
            mainChannel: '0 102 255',
            darkChannel: '0 82 204',
            darkerChannel: '0 45 133',
        },
        secondary: {
            lighter: 'var(--cui-bg-highlight-hovered)',
            light: 'var(--cui-bg-highlight-hovered)',
            main: 'var(--cui-bg-highlight)',
            dark: 'var(--cui-bg-highlight-pressed)',
            darker: 'var(--cui-fg-highlight)',
            mainChannel: '235 194 255',
            darkChannel: '211 150 240',
        },
        error: {
            lighter: 'var(--cui-bg-danger-hovered)',
            light: 'var(--cui-bg-danger-hovered)',
            main: 'var(--cui-bg-danger)',
            dark: 'var(--cui-bg-danger-pressed)',
            darker: 'var(--cui-fg-danger)',
            mainChannel: '224 25 45',
            darkChannel: '180 20 36',
        },
        warning: {
            lighter: 'var(--cui-bg-warning-hovered)',
            light: 'var(--cui-bg-warning-hovered)',
            main: 'var(--cui-bg-warning)',
            dark: 'var(--cui-bg-warning-pressed)',
            darker: 'var(--cui-fg-warning)',
            mainChannel: '255 200 0',
            darkChannel: '204 160 0',
        },
        info: {
            lighter: 'var(--cui-bg-info-hovered)',
            light: 'var(--cui-bg-info-hovered)',
            main: 'var(--cui-bg-info)',
            dark: 'var(--cui-bg-info-pressed)',
            darker: 'var(--cui-fg-info)',
            mainChannel: '0 102 255',
            darkChannel: '0 82 204',
        },
        success: {
            lighter: 'var(--cui-bg-success-hovered)',
            light: 'var(--cui-bg-success-hovered)',
            main: 'var(--cui-bg-success)',
            dark: 'var(--cui-bg-success-pressed)',
            darker: 'var(--cui-fg-success)',
            mainChannel: '0 173 27',
            darkChannel: '0 138 22',
        },
        grey: {
            50: '#F9FAFB',
            100: '#F3F4F6',
            200: '#E5E7EB',
            300: '#D1D5DB',
            400: '#9CA3AF',
            500: '#6B7280',
            600: '#4B5563',
            700: '#374151',
            800: '#1F2937',
            900: '#111827',
            '100Channel': '243 244 246',
            '500Channel': '107 114 128',
            '900Channel': '17 24 39',
        },
        text: {
            primary: 'var(--cui-fg-normal)',
            secondary: 'var(--cui-fg-subtle)',
            disabled: 'var(--cui-fg-disabled)',
            disabledChannel: '107 114 128',
        },
        background: {
            paper: 'var(--cui-bg-normal)',
            default: 'var(--cui-bg-subtle)',
            neutral: 'var(--cui-bg-subtle-hovered)',
            paperChannel: '255 255 255',
            defaultChannel: '243 244 246',
        },
        action: {
            hover: 'rgba(0, 0, 0, 0.04)',
            selected: 'rgba(0, 0, 0, 0.08)',
            disabled: 'rgba(0, 0, 0, 0.26)',
            disabledBackground: 'rgba(0, 0, 0, 0.12)',
            active: 'rgba(0, 0, 0, 0.54)',
        },
        divider: 'var(--cui-border-subtle)',
        shared: {
            inputOutlined: 'rgba(107, 114, 128, 0.2)',
            paperOutlined: 'rgba(107, 114, 128, 0.16)',
            buttonOutlined: 'rgba(107, 114, 128, 0.32)',
        },
        common: {
            black: '#000000',
            white: '#FFFFFF',
            blackChannel: '0 0 0',
            whiteChannel: '255 255 255',
        },
    },
    opacity: {
        soft: {
            bg: 0.08,
            hoverBg: 0.16,
            commonBg: 0.12,
            commonHoverBg: 0.24,
        },
        filled: {
            commonHoverBg: 0.8,
        },
    },
    typography: {
        fontFamily: light.fontStack.default,
        h1: { fontSize: light.typography.headline.one.fontSize, fontWeight: 700 },
        h2: { fontSize: light.typography.headline.two.fontSize, fontWeight: 700 },
        h3: { fontSize: light.typography.headline.three.fontSize, fontWeight: 700 },
        h4: { fontSize: light.typography.headline.four.fontSize, fontWeight: 700 },
        h5: { fontSize: light.typography.subHeadline.fontSize, fontWeight: 700 },
        h6: { fontSize: light.typography.subHeadline.fontSize, fontWeight: 700 },
        subtitle1: { fontSize: light.typography.body.one.fontSize, fontWeight: 600 },
        subtitle2: { fontSize: light.typography.body.two.fontSize, fontWeight: 600 },
        body1: { fontSize: light.typography.body.one.fontSize, fontWeight: 400 },
        body2: { fontSize: light.typography.body.two.fontSize, fontWeight: 400 },
        caption: { fontSize: light.typography.body.two.fontSize, fontWeight: 400 },
        overline: { fontSize: light.typography.body.two.fontSize, fontWeight: 700, textTransform: 'uppercase' },
        fontWeightBold: 700,
        fontWeightSemiBold: 600,
        fontWeightMedium: 500,
        fontWeightRegular: 400,
        pxToRem: (px: number) => `${px / 16}rem`,
    },
    customShadows: {
        z1: 'var(--cui-shadow-navigation)',
        z8: 'var(--cui-shadow-interaction)',
        z20: '0 20px 40px rgba(0,0,0,0.1)',
        dropdown: 'var(--cui-shadow-navigation)',
    },
    borderRadius: {
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
    },
    shape: {
        borderRadius: 8,
    },
    breakpoints: {
        values: {
            xs: 0,
            sm: 600,
            md: 900,
            lg: 1200,
            xl: 1536,
        },
    },
};
